### ISSUE TITLE
Yahoo Mail

### ISSUE THREAD

**Issue by AdKiller** [ewwink/X-Notifier-Reloaded#1]
Could you please fix Yahoo Mail's script?  It would be much appreciated.

**Comment by ewwink** [comment]
Yahoo mail is working properly, check your password.

**Comment by AdKiller** [comment]
Weird it still says "Not checked". I double checked my password, it is correct. The only thing that allows me to check Yahoo Mail right now is POP3. I use Classic Yahoo Mail and have turned on "Allow apps that use less secure sign in" maybe that has something to do with it? Oh well no big deal....

**Comment by ewwink** [comment]
sorry can't help you right now because I can't reproduce the problem, try clear your browser history (cookies) and re-add the account.

**Comment by jeroen1956** [comment]
http://xnotifier.tobwithu.com/dp/node/3601
It will also be added here when I'm done testing and it proves to be stable.

**Comment by AdKiller** [comment]
Thanks a lot now my Yahoo account works!
