### ISSUE TITLE
notification popup

### ISSUE THREAD

**Issue by koullis22** [ewwink/X-Notifier-Reloaded#10]
hello after the update the notification popup doesnt close. Im using ff 55.01 and your latest reloaded version

**Comment by CFBancroft** [comment]
X-notifier Options=> General=> 
When new messages arrive...
[X] Show an alert window
   [X] Auto hide notification (did you check mark? {myself UNcheck and it shows forever until I check email})

**Comment by Loirooriol** [comment]
I have the pref checked and this has been happening for some time. I never looked into it, but seems caused by an error thrown in chrome://xnotifier/content/alert.js:138

```js
  if (prefBranch.getBoolPref("alerts.disableSlidingEffect")) {
    setTimeout(closeAlert, ALERT_DURATION_IMMEDIATE);
    return;
  }
```

    NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff
    (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]

**Comment by koullis22** [comment]
@CFBancroft  yes both are ticked

@Loirooriol good to know someone else noticed..previous version was fine on firefox

**Comment by CFBancroft** [comment]
@koullis22 Thank you for responding...
@Loirooriol Please look into http://xnotifier.tobwithu.com/dp/node/587 that I wrote User Guide 4 years ago... I want to make sure it works on number ** 0? 1? 2? ** it will work with your update?
    0: Do not include
    1: include to folder view only (does not calculate the grand total.)
    2: include to the notification (does calculate the grand total.)

**Comment by Loirooriol** [comment]
@CFBancroft The problem and my patch are unrelated to that. But I tried setting the pref to 1 and I still got notifications, so probably this was broken by something else.
