### ISSUE TITLE
Gmail verification code asked

### ISSUE THREAD

**Issue by p1nkyy** [ewwink/X-Notifier-Reloaded#2]
Hello, thanks for this wonderful fork.
I have used it and now I can open Gmail directly to my inbox, but Gmail is still greyed out. Everytime I force X-Notifier to check, there will be a pop up dialog asking for verification code and my phone will also ask whether a new device is trying to access my mail. What code do I need for this? I have tried my backup codes and also my password to no avail.
![x-notif](https://user-images.githubusercontent.com/7593831/27831619-a3668a68-60f5-11e7-9629-32d0b6929c22.png)

**Comment by ewwink** [comment]
the code is sent via text to your phone, Did you Turn on [Google 2-Step Verification](https://www.google.com/landing/2step/#tab=how-it-works) ? if yes try to turn it off

**Comment by p1nkyy** [comment]
Ah yes, I have 2 step verification turned on. Can't afford to turn it off, so in the mean time, will just let it be greyed out. Thanks for your help.
BTW, no code sent to my phone, just a confirmation asked whether I'm trying to sign in from another device.
