### ISSUE TITLE
Outlook/Hotmail not working & what's going on with the forum?

### ISSUE THREAD

**Issue by thekcool** [ewwink/X-Notifier-Reloaded#27]
I can't login into the forums because of some weird JavaScript error https://i.imgur.com/dT93io2.jpg so...

X-N doesn't seem to be able to check Outlook/Hotmail. The pop up shows my 3 accounts as "not checked". When I click on my individual accounts in the pop up, it takes me to my email account. I got one of those "Hey we're changing things for no good reason" email updates from Microsoft and it seems their changing the login screen (supposedly cosmetically only) so that might be messing up X-N.

X-N 4.2.2 does the same in Chrome.

**Comment by petersellers66** [comment]
I can confirm that it is not possible to register new users due to the java error message on the forum, and I have also had problems with x-notifier and hotmail in the last days, Microsoft makes changes / updates to outlook that lead to x-notifier problems ( accounts as "not checked" ).

**Comment by jeroen1956** [comment]
My (easy) contributions should fix these issues.
So wait for next release...

**Comment by thekcool** [comment]
@jeroen1956 Fixed a few months ago after tobwithu emailed with site login fix. He also provided Outlook/Hotmail fix. 

Guess I'll close this issue out.

**Comment by jeroen1956** [comment]
@thekcool I suspect you don't understand it.
tobwithu does not contribute directly to X-Notifier Reloaded as far as I know.
I do implement his fixes for X-Notifier Reloaded, which is a continued X-notifier vs 3 fork-off.
As long as ewink doesn't release X-Notifier Reloaded 3.5.27 nothing is fixed in this fork-off.
